// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXNhOdW8MaPpd1RYqbQJmYshEcn_8-R3Y',
    appId: '1:405787257554:web:4f0e77e4264bf3cf48db0b',
    messagingSenderId: '405787257554',
    projectId: 'lumo-ea41a',
    authDomain: 'lumo-ea41a.firebaseapp.com',
    storageBucket: 'lumo-ea41a.firebasestorage.app',
    measurementId: 'G-D49L1HG86R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgEUdocAfWuGaRgwrIzLXf5rdDTldkDUU',
    appId: '1:405787257554:android:a57274f29a7c765c48db0b',
    messagingSenderId: '405787257554',
    projectId: 'lumo-ea41a',
    storageBucket: 'lumo-ea41a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhzMsZOUV0GRqtQiqPLii3eCTML1feKpg',
    appId: '1:405787257554:ios:7bcadcdaf67867ce48db0b',
    messagingSenderId: '405787257554',
    projectId: 'lumo-ea41a',
    storageBucket: 'lumo-ea41a.firebasestorage.app',
    iosBundleId: 'com.example.lumoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhzMsZOUV0GRqtQiqPLii3eCTML1feKpg',
    appId: '1:405787257554:ios:7bcadcdaf67867ce48db0b',
    messagingSenderId: '405787257554',
    projectId: 'lumo-ea41a',
    storageBucket: 'lumo-ea41a.firebasestorage.app',
    iosBundleId: 'com.example.lumoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-ulNnATviJvV1BbUXE-Kt32WRXvXO-xM',
    appId: '1:405787257554:web:f6359f618e96fe0c48db0b',
    messagingSenderId: '405787257554',
    projectId: 'lumo-ea41a',
    authDomain: 'lumo-ea41a.firebaseapp.com',
    storageBucket: 'lumo-ea41a.firebasestorage.app',
    measurementId: 'G-63T8Q8HWH3',
  );
}
